version: "3.8"

services:

  db_site_name:
    image: mysql:latest
    container_name: db_site_name
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql

  wordpress_site_name:
    depends_on:
      - db_site_name
    image: wordpress:latest
    container_name: wordpress_site_name
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ${WORDPRESS_VOLUME}:/var/www/html